package com.demo.mycomposeapplication.model

data class Comments(val comment:String)
val arrayList=ArrayList<Comments> ().apply {
    add(Comments(comment = "Great post! Lorem ipsum is classic."))
    add(Comments(comment = "I agree, dummy text is useful for testing layouts.CloudConvert converts your image files online."))
    add(Comments(comment = "Fantastic content!"))
    add(Comments(comment = "I love the way you explain things."))
    add(Comments(comment = "This is really helpful."))
    add(Comments(comment = "Amazing insights!"))
    add(Comments(comment = "Keep up the good work."))
    add(Comments(comment = "Impressive writing style."))
    add(Comments(comment = "You make learning enjoyable."))
    add(Comments(comment = "Looking forward to more content!"))
    add(Comments(comment = "Great post! Lorem ipsum is classic."))
    add(Comments(comment = "I agree, dummy text is useful for testing layouts."))
    add(Comments(comment = "Fantastic content!"))
    add(Comments(comment = "I love the way you explain things."))
    add(Comments(comment = "This is really helpful."))
    add(Comments(comment = "Amazing insights!"))
    add(Comments(comment = "Keep up the good work."))
    add(Comments(comment = "Impressive writing style."))
    add(Comments(comment = "You make learning enjoyable."))
    add(Comments(comment = "Looking forward to more content!"))
    add(Comments(comment = "Great post! Lorem ipsum is classic."))
    add(Comments(comment = "I agree, dummy text is useful for testing layouts."))
    add(Comments(comment = "Fantastic content!"))
    add(Comments(comment = "I love the way you explain things."))
    add(Comments(comment = "This is really helpful."))
    add(Comments(comment = "Amazing insights!"))
    add(Comments(comment = "Keep up the good work."))
    add(Comments(comment = "Impressive writing style."))
    add(Comments(comment = "You make learning enjoyable."))
    add(Comments(comment = "Looking forward to more content!"))
    add(Comments(comment = "Great post! Lorem ipsum is classic."))
    add(Comments(comment = "I agree, dummy text is useful for testing layouts."))
    add(Comments(comment = "Fantastic content!"))
    add(Comments(comment = "I love the way you explain things."))
    add(Comments(comment = "This is really helpful."))
    add(Comments(comment = "Amazing insights!"))
    add(Comments(comment = "Keep up the good work."))
    add(Comments(comment = "Impressive writing style."))
    add(Comments(comment = "You make learning enjoyable."))
    add(Comments(comment = "Looking forward to more content!"))


}
